spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://tasktracker_db:5432/tasktracker}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
logging:
  level:
    com.example.tasktracker: INFO